package com.github.hummel.genst

import lotr.common.world.map.LOTRWaypoint
import net.minecraftforge.common.config.Configuration
import java.io.File
import java.util.*

object Config {
	private var cfg: Configuration? = null
	var on: MutableMap<LOTRWaypoint, Boolean?> = EnumMap(LOTRWaypoint::class.java)

	private fun load() {
		val wp = "waypoints"
		val e = "Enable"
		com.github.hummel.genst.Config.on[LOTRWaypoint.AIN_AL_HARAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ain an-Ah\u00E2r", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FERTILE_VALLEY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ajtiaz an-Ah\u00E2r", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_CITY_CAVES] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Aktun K\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ALDBURG] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Aldburg", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.AMON_ANGREN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Amon Angren", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.AMON_DIN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Amon D\u00EEn", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.AMON_EREB] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Amon Ereb", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DORWINION_HILLS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Amon Gw\u00EEn", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.AMON_HEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Amon Hen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.AMON_LHAW] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Amon Lhaw", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GATE_HERUMOR] = com.github.hummel.genst.Config.cfg?.get(wp, "$e An\u00E2t an-Kh\u00F4rumor", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GATE_FUINUR] = com.github.hummel.genst.Config.cfg?.get(wp, "$e An\u00E2t an-Ph\u00F4in\u00FBr", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARNEN_ROAD_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e An-bat\u00EEna", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ANNUMINAS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ann\u00FAminas", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ARCHET] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Archet", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ARGONATH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Argonath", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GULF_OF_HARAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Arminaz\u00FBl", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ARVEDUI_MINES] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Arvedui's Mines", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MORDOR_FORD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ashen Ford", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_NORTH_CITY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Atalak", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DESERT_RIVER_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ay\u00FBkaph-am\u00E2m", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARNEN_SEA_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e B\u00EAlkadar", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GULF_TRADE_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Bakr\u00EEzad", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BALCARAS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Balcharas", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BARAD_DUR] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Barad-d\u00FBr", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BARAZ_DUM] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Baraz-t\u00FBm", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DALE_PORT] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Bardhaven", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BAZYLAN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Bazylan", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BELEGOST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Belegost", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_SEA_CITY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Belrhuk", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BEORN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Beorn's Hall", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MORANNON] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Black Gate", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BRANDYWINE_BRIDGE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Brandywine Bridge", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BREE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Bree", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARADUIN_BRIDGE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Bridge of Haraduin", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GULF_FORD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Bridge of Harlanhir", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BROCKENBORINGS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Brockenborings", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BUCKLEBURY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Bucklebury", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BYWATER] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Bywater", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CAIR_ANDROS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Cair Andros", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CALEMBEL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Calembel", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CALENHAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Calenhad", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CAPE_OF_FOROCHEL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Cape of Forochel", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CARACH_ANGREN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Carach Angren", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CARAS_GALADHON] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Caras Galadhon", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CARN_DUM] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Carn D\u00FBm", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CARROCK] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Carrock", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CEDAR_ROAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Cedar-woods", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CERIN_AMROTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Cerin Amroth", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.LAKE_HARAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Chunha", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CIRITH_UNGOL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Cirith Ungol", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.COMBE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Combe", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CORSAIRS_LANDING] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Corsair's Landing", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CROSSINGS_ERUI] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Crossings of Erui", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CROSSINGS_OF_HARAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Crossings of Harnen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CROSSINGS_OF_LITHNEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Crossings of Lithnen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CROSSINGS_OF_POROS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Crossings of Poros", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ANDUIN_CROSSROADS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Crossroads of Anduin", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.CROSSROADS_ITHILIEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Crossroads of the Fallen King", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DAINS_HALLS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e D\u00E1in's Halls", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DALE_CITY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Dale", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GREAT_PLAINS_SOUTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Deep Harad", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DEEPHALLOW] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Deephallow", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HELMS_CROSSROADS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Deeping-coomb", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DERNDINGLE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Derndingle", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DIMRILL_DALE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Dimrill Dale", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DOL_AMROTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Dol Amroth", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DOL_GULDUR] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Dol Guldur", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DORWINION_CROSSROADS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Dorwinion Crossroads", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NORTH_DUNLAND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Duneard", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DUNHARROW] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Dunharrow", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NURNEN_WESTERN_SHORE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Dunurnen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BLACK_COAST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Durfalas", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DURTHANG] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Durthang", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DWARROWVALE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Dwarrowvale", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EAGLES_EYRIE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Eagles' Eyrie", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EAST_BIGHT] = com.github.hummel.genst.Config.cfg?.get(wp, "$e East Bight", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.OSGILIATH_EAST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e East Osgiliath", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EAST_PEAK] = com.github.hummel.genst.Config.cfg?.get(wp, "$e East Peak", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EAST_RHOVANION_ROAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e East Rhovanion Gate", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EASTERN_GUARD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Eastern Guard", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EASTMARK] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Eastmark", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EDHELLOND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Edhellond", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EDORAS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Edoras", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EILENACH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Eilenach", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TOWER_HILLS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Elostirion", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_LAKES] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Emerald Lakes", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EMYN_ARNEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Emyn Arnen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ENCHANTED_RIVER] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Enchanted River", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ENTWADE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Entwade", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GULF_EAST_PORT] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ephal\u00F4n", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.EREBOR] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Erebor", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ERECH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Erech", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ERELAS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Erelas", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ERYN_VORN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Eryn Vorn", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ANDUIN_MOUTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ethir Anduin", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARADUIN_MOUTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ethir Haraduin", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ETHRING] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ethring", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FIELD_OF_CELEBRANT] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Field of Celebrant", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SOUTH_DUNLAND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Firwold", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FORD_BRUINEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ford of Bruinen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_NORTH_FORD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ford of Forunen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FORDS_OF_ISEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Fords of Isen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FOREST_GATE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Forest Gate", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FORLINDON] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Forlindon", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FORLOND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Forlond", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FORNOST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Fornost", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NURNEN_NORTHERN_SHORE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Fornurnen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FORSAKEN_INN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Forsaken Inn", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FRAMSBURG] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Framsburg", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FRECA_HOLD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Freca's Hold", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FROGMORTON] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Frogmorton", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.COAST_FORTRESS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e G\u00E2th-azraz\u00E2in", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GARDENS_BERUTHIEL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Gardens of Bar\u00FBphel", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.UMBAR_GATE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Gate of Umbar", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GLADDEN_FIELDS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Gladden Confluence", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GOBLIN_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Goblin Town", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DORWINION_FORD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Golden Ford", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DALE_CROSSROADS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Great Dalish Crossroads", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GREENHOLM] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Greenholm", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GREENWAY_CROSSROADS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Greenway Crossroads", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GRIMSLADE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Grimslade", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HALIFIRIEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Halifirien", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SHADOW_POINT] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Hardorogost", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARLINDON] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Harlindon", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARLOND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Harlond", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NURNEN_SOUTHERN_SHORE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Harnurnen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HAY_GATE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Hay Gate", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HAYSEND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Haysend", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HELMS_DEEP] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Helm's Deep", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HENNETH_ANNUN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Henneth Ann\u00FBn", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HIGH_PASS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e High Pass", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GREAT_PLAINS_EAST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Hill of the Sun", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HIMLING] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Himling", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HOBBITON] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Hobbiton", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARAD_HORN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Horn of Harad", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NIMRODEL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e House of Nimrodel", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GREAT_PLAINS_NORTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Hunters' Haunt", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DESERT_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ijdi-ilel", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.IMLOTH_MELUI] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Imloth Melui", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ISENGARD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Isengard", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SOUTH_DESERT_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Iz\u00EAm-ulzuz", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_EAST_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Karanoda", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_EAST_CITY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Karslan", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GULF_CITY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Kh\u00F4pakadar", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.KHAMUL_TOWER] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Kham\u00FBl's Tower", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.KHAND_FORD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Khandwater Ford", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.OLD_JUNGLE_RUIN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Kimen K\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SANDHILL_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e L\u00EEpha-t\u00FBn", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_CITY_EAST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Lakin P\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.LAST_BRIDGE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Last Bridge", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.LINHIR] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Linhir", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.LITTLE_DELVING] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Little Delving", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.LOND_DAER] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Lond Daer", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.LONG_LAKE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Long Lake", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.LONGBOTTOM] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Longbottom", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_CITY_DEEP] = com.github.hummel.genst.Config.cfg?.get(wp, "$e M\u00FBmak\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MENELTARMA_SUMMIT] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Meneltarma", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MERING_STREAM] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mering Stream", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MICHEL_DELVING] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Michel Delving", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MINAS_MORGUL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Minas Morgul", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MINAS_TIRITH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Minas Tirith", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MINRIMMON] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Min-Rimmon", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DORWINION_PORT] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mirulond", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MORIGOST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mornost", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_SAND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Athras", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_THUNDER] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Belegwaeras", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_CARADHRAS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Caradhras", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_CELEBDIL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Celebdil", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_DOLMED] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Dolmed", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_DOOM] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Doom", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_FANUIDHOL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Fanuidhol", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_GRAM] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Gram", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_GUNDABAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Gundabad", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_GREEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Laegras", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_METHEDRAS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Methedras", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUNT_RERIR] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mount Rerir", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MIRKWOOD_MOUNTAINS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mountains of Mirkwood", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MOUTHS_ISEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Mouths of Isen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GREEN_VALLEY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Nan Harnagorath", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NARDOL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Nardol", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NARGROTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Narroth", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NEEDLEHOLE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Needlehole", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARAD_LAKES] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Nin Haecharad", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARNEN_RIVER_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ninzad\u00EEn", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NOBOTTLE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Nobottle", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NOGROD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Nogrod", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_CITY_CAPITAL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Nohoch K\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NORTH_DOWNS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e North Downs", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NORTH_ITHILIEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e North Ithilien", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.KHAND_NORTH_ROAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e North Khand Road", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MITHLOND_NORTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e North Mithlond", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NORTH_UNDEEP] = com.github.hummel.genst.Config.cfg?.get(wp, "$e North Undeep", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_NORTHEAST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Northern Marches", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.COAST_CITY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Nur\u00EAmin", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.OATBARTON] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Oatbarton", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.OLD_ELF_WAY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Old Elven Way", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.OLD_FORD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Old Ford", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.OLD_RHOVANION] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Old Rhovanion", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ENEDWAITH_ROAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Old South Road", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.OST_IN_EDHIL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ost-in-Edhil", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_CITY_TRADE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Otoch K\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.OVERHILL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Overhill", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_SOUTH_PASS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Pass of Rh\u00FAdel", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.PELARGIR] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Pelargir", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GREEN_HILLS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Pinnath Gelin", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_CITY_WATCH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Pishan K\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RAS_MORTHIL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ras Morthil", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RAUROS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Rauros", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.REDWATER_FORD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Redwater Ford", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_ROAD_WAY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Redway", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_CAPITAL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Rh\u00FAnost", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHOSGOBEL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Rhosgobel", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.NURNEN_EASTERN_SHORE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Rhunurnen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RIVENDELL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Rivendell", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RIVER_GATE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e River Gate", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RUNNING_FORD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Running Ford", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SARN_FORD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Sarn Ford", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SCARY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Scary", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SCATHA] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Scatha's Lair", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BLOOD_RIVER] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Sereghir", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SEREGOST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Seregost", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_CITY_NORTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Shaman P\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SOUTH_DOWNS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e South Downs", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SOUTH_FOROCHEL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e South Forochel", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.MITHLOND_SOUTH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e South Mithlond", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.SOUTH_UNDEEP] = com.github.hummel.genst.Config.cfg?.get(wp, "$e South Undeep", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.RHUN_SOUTHEAST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Southern Marches", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.STADDLE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Staddle", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.STOCK] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Stock", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_CITY_STONE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e T\u00FBnich K\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.BORDER_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Taragal", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TARLANG] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tarlang's Neck", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TARNOST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tarnost", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TAURELONDE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Taurelond\u00EB", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.COAST_RIVER_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Taw\u00EEnen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.THARBAD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tharbad", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.THAURBAND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Thorband", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.THORIN_HALLS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Thorin's Halls", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.THRAIN_HALLS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Thr\u00E1in's Halls", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.THRANDUIL_HALLS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Thranduil's Halls", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TIGHFIELD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tighfield", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TOL_FUIN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tol Fuin", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.ISLE_MIST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tol H\u00EEth", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TOL_MORWEN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tol Morwen", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TROLL_ISLAND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tol Torog", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TOLFALAS_ISLAND] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tolfalas", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GULF_EAST_BAY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Topaz Bay", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TOWN_BONES] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Town of Bones", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TREEBEARD_HILL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Treebeard's Hill", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.THE_TROLLSHAWS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Trollshaws", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.TUCKBOROUGH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Tuckborough", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.HARNEN_BLACK_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ugr\u00EE-zad\u00EEn", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.UMBAR_CITY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Umbar", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GREAT_PLAINS_WEST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Upper Floodplains", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.URUK_HIGHLANDS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Uruk Highlands", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.FELLBEASTS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Vale of the Fell Beasts", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.VALLEY_OF_SPIDERS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Valley of Spiders", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.UDUN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Valley of Ud\u00FBn", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.DORWINION_COURT] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Vintner Court", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WAYMEET] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Waymeet", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WEATHERTOP] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Weathertop", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WELLINGHALL] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Wellinghall", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WEST_GATE] = com.github.hummel.genst.Config.cfg?.get(wp, "$e West Gate", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.OSGILIATH_WEST] = com.github.hummel.genst.Config.cfg?.get(wp, "$e West Osgiliath", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WEST_PEAK] = com.github.hummel.genst.Config.cfg?.get(wp, "$e West Peak", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WHITFURROWS] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Whitfurrows", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WILLOWBOTTOM] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Willowbottom", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WITHERED_HEATH] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Withered Heath", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WITHYWINDLE_VALLEY] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Withywindle Valley", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WOLD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Woldhall", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.WULFBURG] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Wulfburg", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.JUNGLE_CITY_OLD] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Ya'ash K\u00E2h", true)?.boolean
		com.github.hummel.genst.Config.on[LOTRWaypoint.GULF_NORTH_TOWN] = com.github.hummel.genst.Config.cfg?.get(wp, "$e Yaphurushi", true)?.boolean
		if ((com.github.hummel.genst.Config.cfg ?: return).hasChanged()) {
			(com.github.hummel.genst.Config.cfg ?: return).save()
		}
	}

	fun postInit() {
		com.github.hummel.genst.Config.cfg = Configuration(File("config", "Genst II.cfg"))
		com.github.hummel.genst.Config.load()
	}
}