package genst

import lotr.common.world.map.LOTRWaypoint
import net.minecraftforge.common.config.Configuration
import java.io.File
import java.util.*

object GenstConfig {
	private var cfg: Configuration? = null
	private var on: MutableMap<LOTRWaypoint, Boolean?> = EnumMap(LOTRWaypoint::class.java)

	private fun load() {
		val wp = "waypoints"
		on[LOTRWaypoint.AIN_AL_HARAD] = cfg?.get(wp, "Ain an-Ah\u00E2r", true)?.boolean
		on[LOTRWaypoint.FERTILE_VALLEY] = cfg?.get(wp, "Ajtiaz an-Ah\u00E2r", true)?.boolean
		on[LOTRWaypoint.JUNGLE_CITY_CAVES] = cfg?.get(wp, "Aktun K\u00E2h", true)?.boolean
		on[LOTRWaypoint.ALDBURG] = cfg?.get(wp, "Aldburg", true)?.boolean
		on[LOTRWaypoint.AMON_ANGREN] = cfg?.get(wp, "Amon Angren", true)?.boolean
		on[LOTRWaypoint.AMON_DIN] = cfg?.get(wp, "Amon D\u00EEn", true)?.boolean
		on[LOTRWaypoint.AMON_EREB] = cfg?.get(wp, "Amon Ereb", true)?.boolean
		on[LOTRWaypoint.DORWINION_HILLS] = cfg?.get(wp, "Amon Gw\u00EEn", true)?.boolean
		on[LOTRWaypoint.AMON_HEN] = cfg?.get(wp, "Amon Hen", true)?.boolean
		on[LOTRWaypoint.AMON_LHAW] = cfg?.get(wp, "Amon Lhaw", true)?.boolean
		on[LOTRWaypoint.GATE_HERUMOR] = cfg?.get(wp, "An\u00E2t an-Kh\u00F4rumor", true)?.boolean
		on[LOTRWaypoint.GATE_FUINUR] = cfg?.get(wp, "An\u00E2t an-Ph\u00F4in\u00FBr", true)?.boolean
		on[LOTRWaypoint.HARNEN_ROAD_TOWN] = cfg?.get(wp, "An-bat\u00EEna", true)?.boolean
		on[LOTRWaypoint.ANNUMINAS] = cfg?.get(wp, "Ann\u00FAminas", true)?.boolean
		on[LOTRWaypoint.ARCHET] = cfg?.get(wp, "Archet", true)?.boolean
		on[LOTRWaypoint.ARGONATH] = cfg?.get(wp, "Argonath", true)?.boolean
		on[LOTRWaypoint.GULF_OF_HARAD] = cfg?.get(wp, "Arminaz\u00FBl", true)?.boolean
		on[LOTRWaypoint.ARVEDUI_MINES] = cfg?.get(wp, "Arvedui's Mines", true)?.boolean
		on[LOTRWaypoint.MORDOR_FORD] = cfg?.get(wp, "Ashen Ford", true)?.boolean
		on[LOTRWaypoint.RHUN_NORTH_CITY] = cfg?.get(wp, "Atalak", true)?.boolean
		on[LOTRWaypoint.DESERT_RIVER_TOWN] = cfg?.get(wp, "Ay\u00FBkaph-am\u00E2m", true)?.boolean
		on[LOTRWaypoint.HARNEN_SEA_TOWN] = cfg?.get(wp, "B\u00EAlkadar", true)?.boolean
		on[LOTRWaypoint.GULF_TRADE_TOWN] = cfg?.get(wp, "Bakr\u00EEzad", true)?.boolean
		on[LOTRWaypoint.BALCARAS] = cfg?.get(wp, "Balcharas", true)?.boolean
		on[LOTRWaypoint.BARAD_DUR] = cfg?.get(wp, "Barad-d\u00FBr", true)?.boolean
		on[LOTRWaypoint.BARAZ_DUM] = cfg?.get(wp, "Baraz-t\u00FBm", true)?.boolean
		on[LOTRWaypoint.DALE_PORT] = cfg?.get(wp, "Bardhaven", true)?.boolean
		on[LOTRWaypoint.BAZYLAN] = cfg?.get(wp, "Bazylan", true)?.boolean
		on[LOTRWaypoint.BELEGOST] = cfg?.get(wp, "Belegost", true)?.boolean
		on[LOTRWaypoint.RHUN_SEA_CITY] = cfg?.get(wp, "Belrhuk", true)?.boolean
		on[LOTRWaypoint.BEORN] = cfg?.get(wp, "Beorn's Hall", true)?.boolean
		on[LOTRWaypoint.MORANNON] = cfg?.get(wp, "Black Gate", true)?.boolean
		on[LOTRWaypoint.BRANDYWINE_BRIDGE] = cfg?.get(wp, "Brandywine Bridge", true)?.boolean
		on[LOTRWaypoint.BREE] = cfg?.get(wp, "Bree", true)?.boolean
		on[LOTRWaypoint.HARADUIN_BRIDGE] = cfg?.get(wp, "Bridge of Haraduin", true)?.boolean
		on[LOTRWaypoint.GULF_FORD] = cfg?.get(wp, "Bridge of Harlanhir", true)?.boolean
		on[LOTRWaypoint.BROCKENBORINGS] = cfg?.get(wp, "Brockenborings", true)?.boolean
		on[LOTRWaypoint.BUCKLEBURY] = cfg?.get(wp, "Bucklebury", true)?.boolean
		on[LOTRWaypoint.BYWATER] = cfg?.get(wp, "Bywater", true)?.boolean
		on[LOTRWaypoint.CAIR_ANDROS] = cfg?.get(wp, "Cair Andros", true)?.boolean
		on[LOTRWaypoint.CALEMBEL] = cfg?.get(wp, "Calembel", true)?.boolean
		on[LOTRWaypoint.CALENHAD] = cfg?.get(wp, "Calenhad", true)?.boolean
		on[LOTRWaypoint.CAPE_OF_FOROCHEL] = cfg?.get(wp, "Cape of Forochel", true)?.boolean
		on[LOTRWaypoint.CARACH_ANGREN] = cfg?.get(wp, "Carach Angren", true)?.boolean
		on[LOTRWaypoint.CARAS_GALADHON] = cfg?.get(wp, "Caras Galadhon", true)?.boolean
		on[LOTRWaypoint.CARN_DUM] = cfg?.get(wp, "Carn D\u00FBm", true)?.boolean
		on[LOTRWaypoint.CARROCK] = cfg?.get(wp, "Carrock", true)?.boolean
		on[LOTRWaypoint.CEDAR_ROAD] = cfg?.get(wp, "Cedar-woods", true)?.boolean
		on[LOTRWaypoint.CERIN_AMROTH] = cfg?.get(wp, "Cerin Amroth", true)?.boolean
		on[LOTRWaypoint.LAKE_HARAD] = cfg?.get(wp, "Chunha", true)?.boolean
		on[LOTRWaypoint.CIRITH_UNGOL] = cfg?.get(wp, "Cirith Ungol", true)?.boolean
		on[LOTRWaypoint.COMBE] = cfg?.get(wp, "Combe", true)?.boolean
		on[LOTRWaypoint.CORSAIRS_LANDING] = cfg?.get(wp, "Corsair's Landing", true)?.boolean
		on[LOTRWaypoint.CROSSINGS_ERUI] = cfg?.get(wp, "Crossings of Erui", true)?.boolean
		on[LOTRWaypoint.CROSSINGS_OF_HARAD] = cfg?.get(wp, "Crossings of Harnen", true)?.boolean
		on[LOTRWaypoint.CROSSINGS_OF_LITHNEN] = cfg?.get(wp, "Crossings of Lithnen", true)?.boolean
		on[LOTRWaypoint.CROSSINGS_OF_POROS] = cfg?.get(wp, "Crossings of Poros", true)?.boolean
		on[LOTRWaypoint.ANDUIN_CROSSROADS] = cfg?.get(wp, "Crossroads of Anduin", true)?.boolean
		on[LOTRWaypoint.CROSSROADS_ITHILIEN] = cfg?.get(wp, "Crossroads of the Fallen King", true)?.boolean
		on[LOTRWaypoint.DAINS_HALLS] = cfg?.get(wp, "D\u00E1in's Halls", true)?.boolean
		on[LOTRWaypoint.DALE_CITY] = cfg?.get(wp, "Dale", true)?.boolean
		on[LOTRWaypoint.GREAT_PLAINS_SOUTH] = cfg?.get(wp, "Deep Harad", true)?.boolean
		on[LOTRWaypoint.DEEPHALLOW] = cfg?.get(wp, "Deephallow", true)?.boolean
		on[LOTRWaypoint.HELMS_CROSSROADS] = cfg?.get(wp, "Deeping-coomb", true)?.boolean
		on[LOTRWaypoint.DERNDINGLE] = cfg?.get(wp, "Derndingle", true)?.boolean
		on[LOTRWaypoint.DIMRILL_DALE] = cfg?.get(wp, "Dimrill Dale", true)?.boolean
		on[LOTRWaypoint.DOL_AMROTH] = cfg?.get(wp, "Dol Amroth", true)?.boolean
		on[LOTRWaypoint.DOL_GULDUR] = cfg?.get(wp, "Dol Guldur", true)?.boolean
		on[LOTRWaypoint.DORWINION_CROSSROADS] = cfg?.get(wp, "Dorwinion Crossroads", true)?.boolean
		on[LOTRWaypoint.NORTH_DUNLAND] = cfg?.get(wp, "Duneard", true)?.boolean
		on[LOTRWaypoint.DUNHARROW] = cfg?.get(wp, "Dunharrow", true)?.boolean
		on[LOTRWaypoint.NURNEN_WESTERN_SHORE] = cfg?.get(wp, "Dunurnen", true)?.boolean
		on[LOTRWaypoint.BLACK_COAST] = cfg?.get(wp, "Durfalas", true)?.boolean
		on[LOTRWaypoint.DURTHANG] = cfg?.get(wp, "Durthang", true)?.boolean
		on[LOTRWaypoint.DWARROWVALE] = cfg?.get(wp, "Dwarrowvale", true)?.boolean
		on[LOTRWaypoint.EAGLES_EYRIE] = cfg?.get(wp, "Eagles' Eyrie", true)?.boolean
		on[LOTRWaypoint.EAST_BIGHT] = cfg?.get(wp, "East Bight", true)?.boolean
		on[LOTRWaypoint.OSGILIATH_EAST] = cfg?.get(wp, "East Osgiliath", true)?.boolean
		on[LOTRWaypoint.EAST_PEAK] = cfg?.get(wp, "East Peak", true)?.boolean
		on[LOTRWaypoint.EAST_RHOVANION_ROAD] = cfg?.get(wp, "East Rhovanion Gate", true)?.boolean
		on[LOTRWaypoint.EASTERN_GUARD] = cfg?.get(wp, "Eastern Guard", true)?.boolean
		on[LOTRWaypoint.EASTMARK] = cfg?.get(wp, "Eastmark", true)?.boolean
		on[LOTRWaypoint.EDHELLOND] = cfg?.get(wp, "Edhellond", true)?.boolean
		on[LOTRWaypoint.EDORAS] = cfg?.get(wp, "Edoras", true)?.boolean
		on[LOTRWaypoint.EILENACH] = cfg?.get(wp, "Eilenach", true)?.boolean
		on[LOTRWaypoint.TOWER_HILLS] = cfg?.get(wp, "Elostirion", true)?.boolean
		on[LOTRWaypoint.JUNGLE_LAKES] = cfg?.get(wp, "Emerald Lakes", true)?.boolean
		on[LOTRWaypoint.EMYN_ARNEN] = cfg?.get(wp, "Emyn Arnen", true)?.boolean
		on[LOTRWaypoint.ENCHANTED_RIVER] = cfg?.get(wp, "Enchanted River", true)?.boolean
		on[LOTRWaypoint.ENTWADE] = cfg?.get(wp, "Entwade", true)?.boolean
		on[LOTRWaypoint.GULF_EAST_PORT] = cfg?.get(wp, "Ephal\u00F4n", true)?.boolean
		on[LOTRWaypoint.EREBOR] = cfg?.get(wp, "Erebor", true)?.boolean
		on[LOTRWaypoint.ERECH] = cfg?.get(wp, "Erech", true)?.boolean
		on[LOTRWaypoint.ERELAS] = cfg?.get(wp, "Erelas", true)?.boolean
		on[LOTRWaypoint.ERYN_VORN] = cfg?.get(wp, "Eryn Vorn", true)?.boolean
		on[LOTRWaypoint.ANDUIN_MOUTH] = cfg?.get(wp, "Ethir Anduin", true)?.boolean
		on[LOTRWaypoint.HARADUIN_MOUTH] = cfg?.get(wp, "Ethir Haraduin", true)?.boolean
		on[LOTRWaypoint.ETHRING] = cfg?.get(wp, "Ethring", true)?.boolean
		on[LOTRWaypoint.FIELD_OF_CELEBRANT] = cfg?.get(wp, "Field of Celebrant", true)?.boolean
		on[LOTRWaypoint.SOUTH_DUNLAND] = cfg?.get(wp, "Firwold", true)?.boolean
		on[LOTRWaypoint.FORD_BRUINEN] = cfg?.get(wp, "Ford of Bruinen", true)?.boolean
		on[LOTRWaypoint.RHUN_NORTH_FORD] = cfg?.get(wp, "Ford of Forunen", true)?.boolean
		on[LOTRWaypoint.FORDS_OF_ISEN] = cfg?.get(wp, "Fords of Isen", true)?.boolean
		on[LOTRWaypoint.FOREST_GATE] = cfg?.get(wp, "Forest Gate", true)?.boolean
		on[LOTRWaypoint.FORLINDON] = cfg?.get(wp, "Forlindon", true)?.boolean
		on[LOTRWaypoint.FORLOND] = cfg?.get(wp, "Forlond", true)?.boolean
		on[LOTRWaypoint.FORNOST] = cfg?.get(wp, "Fornost", true)?.boolean
		on[LOTRWaypoint.NURNEN_NORTHERN_SHORE] = cfg?.get(wp, "Fornurnen", true)?.boolean
		on[LOTRWaypoint.FORSAKEN_INN] = cfg?.get(wp, "Forsaken Inn", true)?.boolean
		on[LOTRWaypoint.FRAMSBURG] = cfg?.get(wp, "Framsburg", true)?.boolean
		on[LOTRWaypoint.FRECA_HOLD] = cfg?.get(wp, "Freca's Hold", true)?.boolean
		on[LOTRWaypoint.FROGMORTON] = cfg?.get(wp, "Frogmorton", true)?.boolean
		on[LOTRWaypoint.COAST_FORTRESS] = cfg?.get(wp, "G\u00E2th-azraz\u00E2in", true)?.boolean
		on[LOTRWaypoint.GARDENS_BERUTHIEL] = cfg?.get(wp, "Gardens of Bar\u00FBphel", true)?.boolean
		on[LOTRWaypoint.UMBAR_GATE] = cfg?.get(wp, "Gate of Umbar", true)?.boolean
		on[LOTRWaypoint.GLADDEN_FIELDS] = cfg?.get(wp, "Gladden Confluence", true)?.boolean
		on[LOTRWaypoint.GOBLIN_TOWN] = cfg?.get(wp, "Goblin Town", true)?.boolean
		on[LOTRWaypoint.DORWINION_FORD] = cfg?.get(wp, "Golden Ford", true)?.boolean
		on[LOTRWaypoint.DALE_CROSSROADS] = cfg?.get(wp, "Great Dalish Crossroads", true)?.boolean
		on[LOTRWaypoint.GREENHOLM] = cfg?.get(wp, "Greenholm", true)?.boolean
		on[LOTRWaypoint.GREENWAY_CROSSROADS] = cfg?.get(wp, "Greenway Crossroads", true)?.boolean
		on[LOTRWaypoint.GRIMSLADE] = cfg?.get(wp, "Grimslade", true)?.boolean
		on[LOTRWaypoint.HALIFIRIEN] = cfg?.get(wp, "Halifirien", true)?.boolean
		on[LOTRWaypoint.SHADOW_POINT] = cfg?.get(wp, "Hardorogost", true)?.boolean
		on[LOTRWaypoint.HARLINDON] = cfg?.get(wp, "Harlindon", true)?.boolean
		on[LOTRWaypoint.HARLOND] = cfg?.get(wp, "Harlond", true)?.boolean
		on[LOTRWaypoint.NURNEN_SOUTHERN_SHORE] = cfg?.get(wp, "Harnurnen", true)?.boolean
		on[LOTRWaypoint.HAY_GATE] = cfg?.get(wp, "Hay Gate", true)?.boolean
		on[LOTRWaypoint.HAYSEND] = cfg?.get(wp, "Haysend", true)?.boolean
		on[LOTRWaypoint.HELMS_DEEP] = cfg?.get(wp, "Helm's Deep", true)?.boolean
		on[LOTRWaypoint.HENNETH_ANNUN] = cfg?.get(wp, "Henneth Ann\u00FBn", true)?.boolean
		on[LOTRWaypoint.HIGH_PASS] = cfg?.get(wp, "High Pass", true)?.boolean
		on[LOTRWaypoint.GREAT_PLAINS_EAST] = cfg?.get(wp, "Hill of the Sun", true)?.boolean
		on[LOTRWaypoint.HIMLING] = cfg?.get(wp, "Himling", true)?.boolean
		on[LOTRWaypoint.HOBBITON] = cfg?.get(wp, "Hobbiton", true)?.boolean
		on[LOTRWaypoint.HARAD_HORN] = cfg?.get(wp, "Horn of Harad", true)?.boolean
		on[LOTRWaypoint.NIMRODEL] = cfg?.get(wp, "House of Nimrodel", true)?.boolean
		on[LOTRWaypoint.GREAT_PLAINS_NORTH] = cfg?.get(wp, "Hunters' Haunt", true)?.boolean
		on[LOTRWaypoint.DESERT_TOWN] = cfg?.get(wp, "Ijdi-ilel", true)?.boolean
		on[LOTRWaypoint.IMLOTH_MELUI] = cfg?.get(wp, "Imloth Melui", true)?.boolean
		on[LOTRWaypoint.ISENGARD] = cfg?.get(wp, "Isengard", true)?.boolean
		on[LOTRWaypoint.SOUTH_DESERT_TOWN] = cfg?.get(wp, "Iz\u00EAm-ulzuz", true)?.boolean
		on[LOTRWaypoint.RHUN_EAST_TOWN] = cfg?.get(wp, "Karanoda", true)?.boolean
		on[LOTRWaypoint.RHUN_EAST_CITY] = cfg?.get(wp, "Karslan", true)?.boolean
		on[LOTRWaypoint.GULF_CITY] = cfg?.get(wp, "Kh\u00F4pakadar", true)?.boolean
		on[LOTRWaypoint.KHAMUL_TOWER] = cfg?.get(wp, "Kham\u00FBl's Tower", true)?.boolean
		on[LOTRWaypoint.KHAND_FORD] = cfg?.get(wp, "Khandwater Ford", true)?.boolean
		on[LOTRWaypoint.OLD_JUNGLE_RUIN] = cfg?.get(wp, "Kimen K\u00E2h", true)?.boolean
		on[LOTRWaypoint.SANDHILL_TOWN] = cfg?.get(wp, "L\u00EEpha-t\u00FBn", true)?.boolean
		on[LOTRWaypoint.JUNGLE_CITY_EAST] = cfg?.get(wp, "Lakin P\u00E2h", true)?.boolean
		on[LOTRWaypoint.LAST_BRIDGE] = cfg?.get(wp, "Last Bridge", true)?.boolean
		on[LOTRWaypoint.LINHIR] = cfg?.get(wp, "Linhir", true)?.boolean
		on[LOTRWaypoint.LITTLE_DELVING] = cfg?.get(wp, "Little Delving", true)?.boolean
		on[LOTRWaypoint.LOND_DAER] = cfg?.get(wp, "Lond Daer", true)?.boolean
		on[LOTRWaypoint.LONG_LAKE] = cfg?.get(wp, "Long Lake", true)?.boolean
		on[LOTRWaypoint.LONGBOTTOM] = cfg?.get(wp, "Longbottom", true)?.boolean
		on[LOTRWaypoint.JUNGLE_CITY_DEEP] = cfg?.get(wp, "M\u00FBmak\u00E2h", true)?.boolean
		on[LOTRWaypoint.MENELTARMA_SUMMIT] = cfg?.get(wp, "Meneltarma", true)?.boolean
		on[LOTRWaypoint.MERING_STREAM] = cfg?.get(wp, "Mering Stream", true)?.boolean
		on[LOTRWaypoint.MICHEL_DELVING] = cfg?.get(wp, "Michel Delving", true)?.boolean
		on[LOTRWaypoint.MINAS_MORGUL] = cfg?.get(wp, "Minas Morgul", true)?.boolean
		on[LOTRWaypoint.MINAS_TIRITH] = cfg?.get(wp, "Minas Tirith", true)?.boolean
		on[LOTRWaypoint.MINRIMMON] = cfg?.get(wp, "Min-Rimmon", true)?.boolean
		on[LOTRWaypoint.DORWINION_PORT] = cfg?.get(wp, "Mirulond", true)?.boolean
		on[LOTRWaypoint.MORIGOST] = cfg?.get(wp, "Mornost", true)?.boolean
		on[LOTRWaypoint.MOUNT_SAND] = cfg?.get(wp, "Mount Athras", true)?.boolean
		on[LOTRWaypoint.MOUNT_THUNDER] = cfg?.get(wp, "Mount Belegwaeras", true)?.boolean
		on[LOTRWaypoint.MOUNT_CARADHRAS] = cfg?.get(wp, "Mount Caradhras", true)?.boolean
		on[LOTRWaypoint.MOUNT_CELEBDIL] = cfg?.get(wp, "Mount Celebdil", true)?.boolean
		on[LOTRWaypoint.MOUNT_DOLMED] = cfg?.get(wp, "Mount Dolmed", true)?.boolean
		on[LOTRWaypoint.MOUNT_DOOM] = cfg?.get(wp, "Mount Doom", true)?.boolean
		on[LOTRWaypoint.MOUNT_FANUIDHOL] = cfg?.get(wp, "Mount Fanuidhol", true)?.boolean
		on[LOTRWaypoint.MOUNT_GRAM] = cfg?.get(wp, "Mount Gram", true)?.boolean
		on[LOTRWaypoint.MOUNT_GUNDABAD] = cfg?.get(wp, "Mount Gundabad", true)?.boolean
		on[LOTRWaypoint.MOUNT_GREEN] = cfg?.get(wp, "Mount Laegras", true)?.boolean
		on[LOTRWaypoint.MOUNT_METHEDRAS] = cfg?.get(wp, "Mount Methedras", true)?.boolean
		on[LOTRWaypoint.MOUNT_RERIR] = cfg?.get(wp, "Mount Rerir", true)?.boolean
		on[LOTRWaypoint.MIRKWOOD_MOUNTAINS] = cfg?.get(wp, "Mountains of Mirkwood", true)?.boolean
		on[LOTRWaypoint.MOUTHS_ISEN] = cfg?.get(wp, "Mouths of Isen", true)?.boolean
		on[LOTRWaypoint.GREEN_VALLEY] = cfg?.get(wp, "Nan Harnagorath", true)?.boolean
		on[LOTRWaypoint.NARDOL] = cfg?.get(wp, "Nardol", true)?.boolean
		on[LOTRWaypoint.NARGROTH] = cfg?.get(wp, "Narroth", true)?.boolean
		on[LOTRWaypoint.NEEDLEHOLE] = cfg?.get(wp, "Needlehole", true)?.boolean
		on[LOTRWaypoint.HARAD_LAKES] = cfg?.get(wp, "Nin Haecharad", true)?.boolean
		on[LOTRWaypoint.HARNEN_RIVER_TOWN] = cfg?.get(wp, "Ninzad\u00EEn", true)?.boolean
		on[LOTRWaypoint.NOBOTTLE] = cfg?.get(wp, "Nobottle", true)?.boolean
		on[LOTRWaypoint.NOGROD] = cfg?.get(wp, "Nogrod", true)?.boolean
		on[LOTRWaypoint.JUNGLE_CITY_CAPITAL] = cfg?.get(wp, "Nohoch K\u00E2h", true)?.boolean
		on[LOTRWaypoint.NORTH_DOWNS] = cfg?.get(wp, "North Downs", true)?.boolean
		on[LOTRWaypoint.NORTH_ITHILIEN] = cfg?.get(wp, "North Ithilien", true)?.boolean
		on[LOTRWaypoint.KHAND_NORTH_ROAD] = cfg?.get(wp, "North Khand Road", true)?.boolean
		on[LOTRWaypoint.MITHLOND_NORTH] = cfg?.get(wp, "North Mithlond", true)?.boolean
		on[LOTRWaypoint.NORTH_UNDEEP] = cfg?.get(wp, "North Undeep", true)?.boolean
		on[LOTRWaypoint.RHUN_NORTHEAST] = cfg?.get(wp, "Northern Marches", true)?.boolean
		on[LOTRWaypoint.COAST_CITY] = cfg?.get(wp, "Nur\u00EAmin", true)?.boolean
		on[LOTRWaypoint.OATBARTON] = cfg?.get(wp, "Oatbarton", true)?.boolean
		on[LOTRWaypoint.OLD_ELF_WAY] = cfg?.get(wp, "Old Elven Way", true)?.boolean
		on[LOTRWaypoint.OLD_FORD] = cfg?.get(wp, "Old Ford", true)?.boolean
		on[LOTRWaypoint.OLD_RHOVANION] = cfg?.get(wp, "Old Rhovanion", true)?.boolean
		on[LOTRWaypoint.ENEDWAITH_ROAD] = cfg?.get(wp, "Old South Road", true)?.boolean
		on[LOTRWaypoint.OST_IN_EDHIL] = cfg?.get(wp, "Ost-in-Edhil", true)?.boolean
		on[LOTRWaypoint.JUNGLE_CITY_TRADE] = cfg?.get(wp, "Otoch K\u00E2h", true)?.boolean
		on[LOTRWaypoint.OVERHILL] = cfg?.get(wp, "Overhill", true)?.boolean
		on[LOTRWaypoint.RHUN_SOUTH_PASS] = cfg?.get(wp, "Pass of Rh\u00FAdel", true)?.boolean
		on[LOTRWaypoint.PELARGIR] = cfg?.get(wp, "Pelargir", true)?.boolean
		on[LOTRWaypoint.GREEN_HILLS] = cfg?.get(wp, "Pinnath Gelin", true)?.boolean
		on[LOTRWaypoint.JUNGLE_CITY_WATCH] = cfg?.get(wp, "Pishan K\u00E2h", true)?.boolean
		on[LOTRWaypoint.RAS_MORTHIL] = cfg?.get(wp, "Ras Morthil", true)?.boolean
		on[LOTRWaypoint.RAUROS] = cfg?.get(wp, "Rauros", true)?.boolean
		on[LOTRWaypoint.REDWATER_FORD] = cfg?.get(wp, "Redwater Ford", true)?.boolean
		on[LOTRWaypoint.RHUN_ROAD_WAY] = cfg?.get(wp, "Redway", true)?.boolean
		on[LOTRWaypoint.RHUN_CAPITAL] = cfg?.get(wp, "Rh\u00FAnost", true)?.boolean
		on[LOTRWaypoint.RHOSGOBEL] = cfg?.get(wp, "Rhosgobel", true)?.boolean
		on[LOTRWaypoint.NURNEN_EASTERN_SHORE] = cfg?.get(wp, "Rhunurnen", true)?.boolean
		on[LOTRWaypoint.RIVENDELL] = cfg?.get(wp, "Rivendell", true)?.boolean
		on[LOTRWaypoint.RIVER_GATE] = cfg?.get(wp, "River Gate", true)?.boolean
		on[LOTRWaypoint.RUNNING_FORD] = cfg?.get(wp, "Running Ford", true)?.boolean
		on[LOTRWaypoint.SARN_FORD] = cfg?.get(wp, "Sarn Ford", true)?.boolean
		on[LOTRWaypoint.SCARY] = cfg?.get(wp, "Scary", true)?.boolean
		on[LOTRWaypoint.SCATHA] = cfg?.get(wp, "Scatha's Lair", true)?.boolean
		on[LOTRWaypoint.BLOOD_RIVER] = cfg?.get(wp, "Sereghir", true)?.boolean
		on[LOTRWaypoint.SEREGOST] = cfg?.get(wp, "Seregost", true)?.boolean
		on[LOTRWaypoint.JUNGLE_CITY_NORTH] = cfg?.get(wp, "Shaman P\u00E2h", true)?.boolean
		on[LOTRWaypoint.SOUTH_DOWNS] = cfg?.get(wp, "South Downs", true)?.boolean
		on[LOTRWaypoint.SOUTH_FOROCHEL] = cfg?.get(wp, "South Forochel", true)?.boolean
		on[LOTRWaypoint.MITHLOND_SOUTH] = cfg?.get(wp, "South Mithlond", true)?.boolean
		on[LOTRWaypoint.SOUTH_UNDEEP] = cfg?.get(wp, "South Undeep", true)?.boolean
		on[LOTRWaypoint.RHUN_SOUTHEAST] = cfg?.get(wp, "Southern Marches", true)?.boolean
		on[LOTRWaypoint.STADDLE] = cfg?.get(wp, "Staddle", true)?.boolean
		on[LOTRWaypoint.STOCK] = cfg?.get(wp, "Stock", true)?.boolean
		on[LOTRWaypoint.JUNGLE_CITY_STONE] = cfg?.get(wp, "T\u00FBnich K\u00E2h", true)?.boolean
		on[LOTRWaypoint.BORDER_TOWN] = cfg?.get(wp, "Taragal", true)?.boolean
		on[LOTRWaypoint.TARLANG] = cfg?.get(wp, "Tarlang's Neck", true)?.boolean
		on[LOTRWaypoint.TARNOST] = cfg?.get(wp, "Tarnost", true)?.boolean
		on[LOTRWaypoint.TAURELONDE] = cfg?.get(wp, "Taurelond\u00EB", true)?.boolean
		on[LOTRWaypoint.COAST_RIVER_TOWN] = cfg?.get(wp, "Taw\u00EEnen", true)?.boolean
		on[LOTRWaypoint.THARBAD] = cfg?.get(wp, "Tharbad", true)?.boolean
		on[LOTRWaypoint.THAURBAND] = cfg?.get(wp, "Thorband", true)?.boolean
		on[LOTRWaypoint.THORIN_HALLS] = cfg?.get(wp, "Thorin's Halls", true)?.boolean
		on[LOTRWaypoint.THRAIN_HALLS] = cfg?.get(wp, "Thr\u00E1in's Halls", true)?.boolean
		on[LOTRWaypoint.THRANDUIL_HALLS] = cfg?.get(wp, "Thranduil's Halls", true)?.boolean
		on[LOTRWaypoint.TIGHFIELD] = cfg?.get(wp, "Tighfield", true)?.boolean
		on[LOTRWaypoint.TOL_FUIN] = cfg?.get(wp, "Tol Fuin", true)?.boolean
		on[LOTRWaypoint.ISLE_MIST] = cfg?.get(wp, "Tol H\u00EEth", true)?.boolean
		on[LOTRWaypoint.TOL_MORWEN] = cfg?.get(wp, "Tol Morwen", true)?.boolean
		on[LOTRWaypoint.TROLL_ISLAND] = cfg?.get(wp, "Tol Torog", true)?.boolean
		on[LOTRWaypoint.TOLFALAS_ISLAND] = cfg?.get(wp, "Tolfalas", true)?.boolean
		on[LOTRWaypoint.GULF_EAST_BAY] = cfg?.get(wp, "Topaz Bay", true)?.boolean
		on[LOTRWaypoint.TOWN_BONES] = cfg?.get(wp, "Town of Bones", true)?.boolean
		on[LOTRWaypoint.TREEBEARD_HILL] = cfg?.get(wp, "Treebeard's Hill", true)?.boolean
		on[LOTRWaypoint.THE_TROLLSHAWS] = cfg?.get(wp, "Trollshaws", true)?.boolean
		on[LOTRWaypoint.TUCKBOROUGH] = cfg?.get(wp, "Tuckborough", true)?.boolean
		on[LOTRWaypoint.HARNEN_BLACK_TOWN] = cfg?.get(wp, "Ugr\u00EE-zad\u00EEn", true)?.boolean
		on[LOTRWaypoint.UMBAR_CITY] = cfg?.get(wp, "Umbar", true)?.boolean
		on[LOTRWaypoint.GREAT_PLAINS_WEST] = cfg?.get(wp, "Upper Floodplains", true)?.boolean
		on[LOTRWaypoint.URUK_HIGHLANDS] = cfg?.get(wp, "Uruk Highlands", true)?.boolean
		on[LOTRWaypoint.FELLBEASTS] = cfg?.get(wp, "Vale of the Fell Beasts", true)?.boolean
		on[LOTRWaypoint.VALLEY_OF_SPIDERS] = cfg?.get(wp, "Valley of Spiders", true)?.boolean
		on[LOTRWaypoint.UDUN] = cfg?.get(wp, "Valley of Ud\u00FBn", true)?.boolean
		on[LOTRWaypoint.DORWINION_COURT] = cfg?.get(wp, "Vintner Court", true)?.boolean
		on[LOTRWaypoint.WAYMEET] = cfg?.get(wp, "Waymeet", true)?.boolean
		on[LOTRWaypoint.WEATHERTOP] = cfg?.get(wp, "Weathertop", true)?.boolean
		on[LOTRWaypoint.WELLINGHALL] = cfg?.get(wp, "Wellinghall", true)?.boolean
		on[LOTRWaypoint.WEST_GATE] = cfg?.get(wp, "West Gate", true)?.boolean
		on[LOTRWaypoint.OSGILIATH_WEST] = cfg?.get(wp, "West Osgiliath", true)?.boolean
		on[LOTRWaypoint.WEST_PEAK] = cfg?.get(wp, "West Peak", true)?.boolean
		on[LOTRWaypoint.WHITFURROWS] = cfg?.get(wp, "Whitfurrows", true)?.boolean
		on[LOTRWaypoint.WILLOWBOTTOM] = cfg?.get(wp, "Willowbottom", true)?.boolean
		on[LOTRWaypoint.WITHERED_HEATH] = cfg?.get(wp, "Withered Heath", true)?.boolean
		on[LOTRWaypoint.WITHYWINDLE_VALLEY] = cfg?.get(wp, "Withywindle Valley", true)?.boolean
		on[LOTRWaypoint.WOLD] = cfg?.get(wp, "Woldhall", true)?.boolean
		on[LOTRWaypoint.WULFBURG] = cfg?.get(wp, "Wulfburg", true)?.boolean
		on[LOTRWaypoint.JUNGLE_CITY_OLD] = cfg?.get(wp, "Ya'ash K\u00E2h", true)?.boolean
		on[LOTRWaypoint.GULF_NORTH_TOWN] = cfg?.get(wp, "Yaphurushi", true)?.boolean
		if ((cfg ?: return).hasChanged()) {
			(cfg ?: return).save()
		}
	}

	fun postInit() {
		cfg = Configuration(File("config", "Genst II.cfg"))
		load()
	}

	fun isNotForbidden(wp: LOTRWaypoint): Boolean? {
		return on[wp]
	}
}